### ISSUE TITLE
ERROR: UndefVarError: warn not defined

### ISSUE THREAD

**Issue by wentasah** [gcalderone/CMPFit.jl#2]
Hi,

I get the following error with Julia 1.4.1:

```
ERROR: UndefVarError: warn not defined
Stacktrace:
 [1] cmpfit(::CMPFit.var"#cmpfit_callback#9"{Array{Float64,1},Array{Float64,1},Array{Float64,1},typeof(Thermobench.model)}, ::Array{Float64,1}; parinfo::Array{CMPFit.Parinfo,1}, config::Nothing) at /home/wsh/.julia/packages/CMPFit/OTtF8/src/CMPFit.jl:275
```

**Comment by wentasah** [comment]
It seems to be fixed in the latest version. But https://github.com/JuliaRegistries/General/blob/master/C/CMPFit/Versions.toml knows only about 0.2.1.

**Comment by gcalderone** [comment]
Yes, I still didn't registered a new one because I wanted to play a bit with artifacts, to check if I could directly distribute a binary version of the underlying C library (rather than build it).  

This currently works only on Linux (branch `CMPFit#usingArtifacts`) but I have not been able to test it on OSX, and I have no idea on how to handle MS windows...
